### ISSUE TITLE
.bind is bad

### ISSUE THREAD

**Issue by f0rmat1k** [Promo/scrollissimo#11]
1. It's slower and requires more memory. Can we remove bind's ?
2. What it does mean?
```javascript
//tick
                this.id = win._rAF(this.step.bind(this));
```
I removed it, and test passed. And i don't see usage of this.

**Comment by frux** [comment]
1. Don't think it's possible.
2. It means:
```js
win._rAF === requestAnimationFrame
```
And I need to have access to ```this``` into rAF callback.
