### ISSUE TITLE
Minimal IE version?

### ISSUE THREAD

**Issue by f0rmat1k** [Promo/scrollissimo#12]
Which minimal IE do u support?
I see in some places code for ie8, e.g. innerHeight:
```return isNaN(win.innerHeight) ? win.clientHeight : win.innerHeight;```

but then you use `addEventListener`, which works only with lte IE9.
We should support IE8 fully or remove code for it.

**Comment by frux** [comment]
I decided that support Internet Explorer 8 is useless. Will remove unnecessary code.

**Comment by frux** [comment]
Done https://github.com/Promo/scrollissimo/commit/caafbf9fec1924ba8124261bae0bd8db92b02e2e
