### ISSUE TITLE
Readme.md fix for case of plugin name scrollissimo to Scrollissimo

### ISSUE THREAD

**Issue by gaikwad411** [Promo/scrollissimo#22]
As per my observation, case of plugin name Scrollissimo is wrong in read me file.
The code does not work when you copy paste it. :)
It worked when I changed "scrollissimo" to "Scrollissimo"

**Comment by frux** [comment]
What file do you copy from? scrollissimo.js or scrollissimo.es5.js?

**Comment by gaikwad411** [comment]
I have used scrollissimo/dist/scrollissimo.min.js

**Comment by frux** [comment]
It's very strange because it contains
```js
global.scrollissimo=mod.exports;
```
So ``scrollissimo`` should work.

**Comment by frux** [comment]
Oh. I got it. You have used version 0.6.0. Yes, it contains error. It will be fixed in 0.7.0.

**Comment by gaikwad411** [comment]
Ok, There is also other typo in readme which user can not directly use by copy paste. 
It is that, element have been added as `<div id="Divy"></div>`
and in next line of code It is being referenced as `document.getElementById('divy')` , here MDN says that
it is case sensitive [https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById](url) and that is why direct copy paste will not work, which will be preferred way of trying the things.

**Comment by frux** [comment]
You're right. Fixed this in a3ac1184ee803358fbf5b061ffb0c0f158a6dd9d. Thank you!
